[package]
name = "sqlite3-fts5-html"
license = "Public Domain"
homepage = "https://github.com/streetwriters/sqlite3-fts5-html"
repo = "https://github.com/streetwriters/sqlite3-fts5-html"
description = "A pseudo tokenizer for SQLite3 FTS5 to strip HTML tags"
authors = ["Abdullah Atta"]
git_tag_format = "v$VERSION"

[targets]
github_releases = {}
amalgamation = {include=["fts5-html.c", "fts5-html.h"]}

npm = {}
