name: Test

on:
  workflow_dispatch:
  push:
    branch: "master"
  pull_request:
    types:
      - "ready_for_review"
      - "opened"
      - "synchronize"
      - "reopened"

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install lemon tcl

      - name: Clone html5lib-tests
        run: |
          git clone https://github.com/html5lib/html5lib-tests.git tests/html5lib-tests

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Run tests
        run: make test

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone html5lib-tests
        run: |
          git clone https://github.com/html5lib/html5lib-tests.git tests/html5lib-tests

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Run tests
        run: nmake /f Makefile.vc test

  build-windows-aarch64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm64
      - run: nmake /f Makefile.vc ARCH=ARM64 loadable

  build-ios-extensions:
    runs-on: ${{ matrix.platforms.runner }}
    strategy:
      fail-fast: false
      matrix:
        platforms: [
            {
              name: ios-aarch64,
              target: arm64-apple-ios,
              arch: arm64,
              sdk: iphoneos,
              runner: macos-14,
            },
            #{
            #  name: ios-x86_64,
            #  target: x86_64-apple-ios,
            #  sdk: iphoneos,
            #  runner: macos-12,
            #},
            {
              name: iossimulator-aarch64,
              target: arm64-apple-ios-simulator,
              arch: arm64,
              sdk: iphonesimulator,
              runner: macos-14,
            },
            {
              name: iossimulator-x86_64,
              target: x86_64-apple-ios-simulator,
              arch: x86_64,
              sdk: iphonesimulator,
              runner: macos-14,
            },
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - run: make CFLAGS="-target ${{ matrix.platforms.target }} -isysroot $(xcrun -sdk ${{ matrix.platforms.sdk }} --show-sdk-path) -fembed-bitcode -DNDEBUG=1 -DCMAKE_OSX_ARCHITECTURES=${{ matrix.platforms.arch }}" loadable

  test-macos:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone html5lib-tests
        run: |
          git clone https://github.com/html5lib/html5lib-tests.git tests/html5lib-tests

      - name: Install dependencies
        run: |
          brew install lemon
          brew install tcl-tk

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Run tests
        run: make test
